import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Card from '../components/Card';

// const API_URL = "https://rickandmortyapi.com/api/character";

function Home() {


  // const listPersonajes = [
  //   {
  //     name: "Benjamin",
  //     image: null,
  //   },
  //   {
  //     name: "Seba",
  //     image: null,
  //   },
  //   {
  //     name: "Carlos",
  //     image: null,
  //   },
  //   {
  //     name: "Mike",
  //     image: null,
  //   },
  //   {
  //     name: "Marfull",
  //     image: null,
  //   }
  // ];

  const [characters, setCharacters] = useState([]);

  // useEffect(() => {
  //   fetch(API_URL)
  //     .then(res => res.json())
  //     .then( (data) => {
  //       setCharacters(characters, ...data.results);
  //     }).catch( (error) => {
  //       console.log(error);
  //     })
  // }, []);

  useEffect(() => {
    fetch("http://localhost:3000/api/characters")
      .then(res => res.json())
      .then( (data) => {
        setCharacters(data.data.results);
      }).catch( (error) => {
        console.log(error);
      })
    }, []);


  const personajes = () => {
    return (
      <div className="container text-center">
        <h1>RICK & MORTY</h1>
        <div className="row">
          {characters && characters.map((personaje, index) => (
            <div className="col-4" key={index}>
              <Card name={personaje.name} image={personaje.image}></Card>
            </div>
          ))}
        </div>
      </div>
    );
  };


  return (
    <div>
      <Head>
        <title>APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {personajes()}

      {/* <Link href="/contactos"> Contactos</Link> */}
    </div>
  )
};

// export async function getServerSideProps() {
//   const res = await fetch(API_URL);
//   const data = await res.json();

//   // console.log("servidor", data);

//   return { props: { data }}
// }

export default Home;
